apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Release.Name }}-seed
  namespace: 0oqfemca-rest-dev
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "1"
    "helm.sh/hook-delete-policy": before-hook-creation
spec:
  template:
    metadata:
    spec:
      restartPolicy: OnFailure
      initContainers:
        - name: wait-for-db
          image: alpine:3.18
          env:
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: application-pguser-admin
                  key: host
            - name: DB_PORT
              valueFrom:
                secretKeyRef:
                  name: application-pguser-admin
                  key: port
          command: ['sh', '-c', 'until nc -vz $DB_HOST $DB_PORT; do echo "Waiting for database at $DB_HOST:$DB_PORT..."; sleep 2; done;']
      containers:
      - name: init-data
        image: postgres:15-alpine
        env:
        - name: PGHOST
          valueFrom:
            secretKeyRef:
              name: application-pguser-admin
              key: host
        - name: PGPORT
          valueFrom:
            secretKeyRef:
              name: application-pguser-admin
              key: port
        - name: PGDATABASE
          valueFrom:
            secretKeyRef:
              name: application-pguser-admin
              key: dbname
        - name: PGUSER
          valueFrom:
            secretKeyRef:
              name: application-pguser-admin
              key: user
        - name: PGPASSWORD
          valueFrom:
            secretKeyRef:
              name: application-pguser-admin
              key: password
        command:
        - sh
        - -c
        - |
          echo "Starting database initialization for database: $PGDATABASE..."
          psql -f /scripts/init-db.sql
          echo "Database initialization completed successfully!"
        volumeMounts:
        - name: sql-script
          mountPath: /scripts
      volumes:
      - name: sql-script
        configMap:
          name: {{ .Release.Name }}-seed
