{{- if .Values.serverDefinitions.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pgadmin-eso-secret-reader
  labels:
    {{- include "pgadmin.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: pgadmin-eso-secret-reader
subjects:
  - kind: ServiceAccount
    name: pgadmin-eso-sa
    namespace: {{ .Release.Namespace }}
{{- end }}
