{{- if .Values.serverDefinitions.enabled }}
apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: pgadmin-k8s-store
spec:
  provider:
    kubernetes:
      remoteNamespace: {{ .Release.Namespace }}
      server:
        caProvider:
          type: ConfigMap
          name: kube-root-ca.crt
          key: ca.crt
      auth:
        serviceAccount:
          name: pgadmin-eso-sa
{{- end }}
